// demo/src/react/DemoApp.tsx
/*
 *  Copyright IBM Corp. 2025, 2026
 *
 *  This source code is licensed under the Apache-2.0 license found in the
 *  LICENSE file in the root directory of this source tree.
 *
 *  @license
 */

import '@carbon/ai-chat/css/chat-sidebar-layout.css';
import './DemoApp.css';
import '@carbon/styles/css/styles.css';
import '@carbon/ai-chat-components/es/components/chat-shell/index.js';

import {
  BusEvent,
  BusEventMessageItemCustom,
  BusEventType,
  BusEventViewChange,
  BusEventViewPreChange,
  BusEventWorkspacePreOpen,
  BusEventWorkspaceOpen,
  ChatContainer,
  ChatCustomElement,
  ChatInstance,
  FeedbackInteractionType,
  MarkdownRendererTableArgs,
  PublicConfig,
  RenderUserDefinedState,
  RenderCustomMessageFooter,
  RenderCustomRequestFooter,
  ServiceDesk,
  ServiceDeskFactoryParameters,
} from '@carbon/ai-chat';
import { AISkeletonPlaceholder } from '@carbon/react';
import React, { useCallback, useEffect, useMemo, useState } from 'react';

import { Settings } from '../framework/types';
import { UserDefinedResponseExample } from './UserDefinedResponseExample';
import { WriteableElementExample } from './WriteableElementExample';
import { WorkspaceWriteableElementExample } from './WorkspaceWriteableElementExample';
import { CustomFooterExample } from './CustomFooterExample';
import { CustomRequestFooterExample } from './CustomRequestFooterExample';
import { HistoryWriteableElementExample } from './HistoryWriteableElementExample';
import {
  ExplainabilityPopoverActions,
  ExplainabilityPopoverContent,
} from './ExplainabilityPopoverExample';
import { MockServiceDesk } from '../mockServiceDesk/mockServiceDesk';

const sleep = (milliseconds: number) =>
  new Promise((resolve) => setTimeout(resolve, milliseconds));

const serviceDeskFactory = (parameters: ServiceDeskFactoryParameters) =>
  Promise.resolve(new MockServiceDesk(parameters) as ServiceDesk);

/**
 * Stand-in for a consumer's own table component. The class is the only hook a
 * page stylesheet has: the chat's own CSS lives in a shadow root, so a page
 * rule that lands on this node proves the chat put it in page light DOM.
 */
function renderCustomTable({ headers, rows }: MarkdownRendererTableArgs) {
  return (
    <div
      className="demo-markdown-custom-table"
      data-testid="demo_markdown_custom_table">
      {`Custom table: ${headers.length} columns, ${rows.length} rows`}
    </div>
  );
}

interface AppProps {
  config: PublicConfig;
  settings: Settings;
  onChatInstanceReady?: (instance: ChatInstance) => void;
}

function DemoApp({ config, settings, onChatInstanceReady }: AppProps) {
  const [sideBarOpen, setSideBarOpen] = useState(false);
  const [sideBarClosing, setSideBarClosing] = useState(false);
  const [workspaceExpanded, setWorkspaceExpanded] = useState(false);
  const [workspaceAnimating, setWorkspaceAnimating] = useState<
    'expanding' | 'contracting' | null
  >(null);
  const [instance, setInstance] = useState<ChatInstance | null>(null);
  const [stateText, setStateText] = useState<string>('Initial text');
  const isSidebarLayout = settings.layout === 'sidebar';

  useEffect(() => {
    // This demo continuously updates parent state to exercise live host-state
    // propagation into writeable elements / user-defined responses. It also adds
    // constant noise when profiling the chat's render performance, so it can be
    // turned off with the `?disableParentStateTimer` query param.
    if (
      typeof window !== 'undefined' &&
      new URLSearchParams(window.location.search).has('disableParentStateTimer')
    ) {
      return undefined;
    }
    const id = setInterval(() => setStateText(Date.now().toString()), 2000);
    return () => clearInterval(id);
  }, []);
  /**
   * Handler for user_defined response types. You can just have a switch statement here and return the right component
   * depending on which component should be rendered.
   */
  const renderUserDefinedResponse = useCallback(
    (state: RenderUserDefinedState, _instance: ChatInstance) => {
      const { messageItem, partialItems } = state;
      // The event here will contain details for each user defined response that needs to be rendered.
      if (messageItem) {
        switch (messageItem.user_defined?.user_defined_type) {
          case 'green':
            return (
              <UserDefinedResponseExample
                text={messageItem.user_defined.text as string}
                parentStateText={stateText}
              />
            );
          case 'response-stopped':
            return <>Custom user_defined response stopped message.</>;
          default:
            return undefined;
        }
      }

      if (partialItems) {
        switch (partialItems[0].user_defined?.user_defined_type) {
          case 'green': {
            // The partial members are not concatenated, you get a whole array of chunks so you can special handle
            // concatenation as you want.
            const text = partialItems
              .map((item) => item.user_defined?.text)
              .join('');
            return (
              <UserDefinedResponseExample
                text={text}
                parentStateText={stateText}
              />
            );
          }
          default: {
            // Default to just showing a skeleton state for user_defined responses types we don't want to have special
            // streaming behavior for.
            return <AISkeletonPlaceholder className="fullSkeleton" />;
          }
        }
      }
    },
    [stateText]
  );

  /**
   * Handler for custom footer slot.
   */
  const renderCustomMessageFooter: RenderCustomMessageFooter = useCallback(
    (slotName, message, messageItem, instance, additionalData) => {
      return (
        <CustomFooterExample
          slotName={slotName}
          message={message}
          messageItem={messageItem}
          instance={instance}
          additionalData={additionalData}
        />
      );
    },
    []
  );

  /**
   * Handler for the footer slot below a user message.
   */
  const renderCustomRequestFooter: RenderCustomRequestFooter = useCallback(
    (_slotName, message, _instance) => {
      return <CustomRequestFooterExample message={message} />;
    },
    []
  );

  /**
   * You can return a React element for each slot.
   */
  const historyIsMobile =
    instance?.getState().customPanels.history.isMobile ?? false;

  // Memoize history panel separately to prevent rerenders when stateText changes
  const historyPanelElement = useMemo(
    () => (
      <HistoryWriteableElementExample
        instance={instance as ChatInstance}
        isMobile={historyIsMobile}
      />
    ),
    [instance, historyIsMobile]
  );

  const allWriteableElements = useMemo(
    () => ({
      headerBottomElement: (
        <WriteableElementExample
          location="headerBottomElement"
          parentStateText={stateText}
        />
      ),
      headerFixedActionsElement: (
        <WriteableElementExample
          location="headerFixedActionsElement"
          parentStateText={stateText}
        />
      ),
      welcomeNodeBeforeElement: (
        <WriteableElementExample
          location="welcomeNodeBeforeElement"
          parentStateText={stateText}
        />
      ),
      homeScreenHeaderBottomElement: (
        <WriteableElementExample
          location="homeScreenHeaderBottomElement"
          parentStateText={stateText}
        />
      ),
      homeScreenAfterStartersElement: (
        <WriteableElementExample
          location="homeScreenAfterStartersElement"
          parentStateText={stateText}
        />
      ),
      homeScreenBeforeInputElement: (
        <WriteableElementExample
          location="homeScreenBeforeInputElement"
          parentStateText={stateText}
        />
      ),
      beforeInputElement: (
        <WriteableElementExample
          location="beforeInputElement"
          parentStateText={stateText}
        />
      ),
      afterInputElement: (
        <WriteableElementExample
          location="afterInputElement"
          parentStateText={stateText}
        />
      ),
      promptLineActionsEnd: (
        <WriteableElementExample
          location="promptLineActionsEnd"
          parentStateText={stateText}
        />
      ),
      promptLineSendButtonStart: (
        <WriteableElementExample
          location="promptLineSendButtonStart"
          parentStateText={stateText}
        />
      ),
      footerElement: (
        <WriteableElementExample
          location="footerElement"
          parentStateText={stateText}
        />
      ),
      aiTooltipAfterDescriptionElement: (
        <WriteableElementExample
          location="aiTooltipAfterDescriptionElement"
          parentStateText={stateText}
        />
      ),
      explainabilityPopoverContent: <ExplainabilityPopoverContent />,
      explainabilityPopoverActions: <ExplainabilityPopoverActions />,
      workspacePanelElement: (
        <WorkspaceWriteableElementExample
          location="workspacePanelElement"
          instance={instance as ChatInstance}
          parentStateText={stateText}
        />
      ),
      historyPanelElement,
    }),
    [instance, historyPanelElement, stateText]
  );

  /**
   * Determines which slots to render based on settings and config.
   * - If writeableElements is true: show all elements
   * - If writeableElements is false AND homescreen is custom: show only home screen specific elements
   * - Otherwise: show no elements
   */
  const renderWriteableElements = useMemo(() => {
    const isCustomHomeScreen = config.homescreen?.customContentOnly === true;
    const showAllWriteableElements = settings.writeableElements === 'true';
    const showHomeScreenElements =
      !showAllWriteableElements && isCustomHomeScreen;

    let elements;

    if (showAllWriteableElements) {
      const {
        explainabilityPopoverContent: _explainabilityPopoverContent,
        explainabilityPopoverActions: _explainabilityPopoverActions,
        ...writeableElements
      } = allWriteableElements;
      elements = writeableElements;
    } else if (showHomeScreenElements) {
      elements = {
        homeScreenHeaderBottomElement:
          allWriteableElements.homeScreenHeaderBottomElement,
        homeScreenAfterStartersElement:
          allWriteableElements.homeScreenAfterStartersElement,
      };
    } else {
      elements = {};
    }

    return {
      ...elements,
      workspacePanelElement: allWriteableElements.workspacePanelElement,
      historyPanelElement: allWriteableElements.historyPanelElement,
      explainabilityPopoverContent:
        allWriteableElements.explainabilityPopoverContent,
      explainabilityPopoverActions:
        allWriteableElements.explainabilityPopoverActions,
    };
  }, [allWriteableElements, settings.writeableElements, config.homescreen]);

  const onBeforeRender = (instance: ChatInstance) => {
    setInstance(instance);
    // Notify parent component that instance is ready
    onChatInstanceReady?.(instance);

    // Here we are registering an event listener for if someone clicks on a button that throws
    // a client side event.
    instance.on({
      type: BusEventType.MESSAGE_ITEM_CUSTOM,
      handler: customButtonHandler,
    });

    // here we add a handler to the workspace pre open and open events
    instance.on({
      type: BusEventType.WORKSPACE_PRE_OPEN,
      handler: (event: BusEvent) => {
        const { data } = event as BusEventWorkspacePreOpen;
        console.log(
          data,
          'This event can be used to load additional resources into the workspace while displaying a manual loading state. in your writeableElement'
        );
        // Expand sidebar when workspace is opening (only in sidebar layout)
        if (isSidebarLayout) {
          console.log('Expanding sidebar - workspace opening');
          setWorkspaceAnimating('expanding');
          setWorkspaceExpanded(true);
        }
      },
    });

    instance.on({
      type: BusEventType.WORKSPACE_OPEN,
      handler: customWorkspaceOpenHandler,
    });

    // Listen for workspace pre-close to contract the sidebar
    instance.on({
      type: BusEventType.WORKSPACE_PRE_CLOSE,
      handler: () => {
        // Contract sidebar when workspace is closing (only in sidebar layout)
        if (isSidebarLayout) {
          console.log('Contracting sidebar - workspace closing');
          setWorkspaceAnimating('contracting');
          setWorkspaceExpanded(false);
        }
      },
    });

    instance.on({
      type: BusEventType.HISTORY_PANEL_NEW_CHAT,
      handler: () => window.alert('Creating new chat from header menu'),
    });

    // Handle feedback event.
    instance.on({ type: BusEventType.FEEDBACK, handler: feedbackHandler });
  };

  /**
   * Listens for view changes on the AI chat.
   */
  const onViewChange = isSidebarLayout
    ? (event: BusEventViewChange, _instance: ChatInstance) => {
        if (event.newViewState.mainWindow) {
          setSideBarOpen(true);
        } else {
          setSideBarOpen(false);
          setSideBarClosing(false);
        }
      }
    : undefined;

  /**
   * Handles pre-view-change lifecycle for sidebar transitions.
   */
  const onViewPreChange = isSidebarLayout
    ? async (event: BusEventViewPreChange, _instance: ChatInstance) => {
        if (!event.newViewState.mainWindow) {
          setSideBarClosing(true);
          await sleep(250);
        }
      }
    : undefined;

  // Handle transitionend to remove animation classes
  const handleTransitionEnd = useCallback((event: React.TransitionEvent) => {
    // Only handle width transitions
    if (event.propertyName === 'width') {
      setWorkspaceAnimating(null);
    }
  }, []);

  // And some logic to add the right classname to our custom element depending
  // on what mode we are in. The sidebar layout uses the shipped
  // `cds-aichat-sidebar` classes plus the workspace expand/contract modifiers.
  let className = '';
  if (settings.layout === 'fullscreen') {
    className = 'fullScreen';
  } else if (isSidebarLayout) {
    className = 'cds-aichat-sidebar';
    if (workspaceExpanded) {
      className += ' cds-aichat-sidebar--expanded';
    }
    if (workspaceAnimating === 'expanding') {
      className += ' cds-aichat-sidebar--expanding';
    } else if (workspaceAnimating === 'contracting') {
      className += ' cds-aichat-sidebar--contracting';
    }
    if (sideBarClosing) {
      className += ' cds-aichat-sidebar--closing';
    } else if (!sideBarOpen) {
      className += ' cds-aichat-sidebar--closed';
    }
  }

  const headerConfig = {
    ...config.header,
    hideDefaultAiLabelContent: true,
  };

  // Memoized because `markdown` is compared by reference: a fresh literal each
  // render would rebuild every custom-renderer host on every parent update.
  const markdownConfig = useMemo(
    () =>
      settings.markdownCustomRenderers === 'true'
        ? { ...config.markdown, customRenderers: { table: renderCustomTable } }
        : config.markdown,
    [config.markdown, settings.markdownCustomRenderers]
  );

  return settings.layout === 'float' ? (
    <ChatContainer
      {...config}
      header={headerConfig}
      markdown={markdownConfig}
      onBeforeRender={onBeforeRender}
      renderUserDefinedResponse={renderUserDefinedResponse}
      renderCustomMessageFooter={renderCustomMessageFooter}
      renderCustomRequestFooter={renderCustomRequestFooter}
      renderWriteableElements={renderWriteableElements}
      serviceDeskFactory={serviceDeskFactory}
    />
  ) : (
    <div onTransitionEnd={handleTransitionEnd}>
      <ChatCustomElement
        {...config}
        header={headerConfig}
        markdown={markdownConfig}
        className={className as string}
        onViewPreChange={onViewPreChange}
        onViewChange={onViewChange}
        onBeforeRender={onBeforeRender}
        renderUserDefinedResponse={renderUserDefinedResponse}
        renderCustomMessageFooter={renderCustomMessageFooter}
        renderCustomRequestFooter={renderCustomRequestFooter}
        renderWriteableElements={renderWriteableElements}
        serviceDeskFactory={serviceDeskFactory}
      />
    </div>
  );
}

/**
 * Handles when the user submits feedback.
 */
function feedbackHandler(event: any) {
  if (event.interactionType === FeedbackInteractionType.SUBMITTED) {
    const { ...reportData } = event;
    setTimeout(() => {
      // eslint-disable-next-line no-alert
      window.alert(JSON.stringify(reportData, null, 2));
    });
  }
}

/**
 * Listens for clicks from buttons with custom events attached.
 */
function customButtonHandler(event: BusEvent) {
  const { messageItem } = event as BusEventMessageItemCustom;
  // The 'custom_event_name' property comes from the button response type with button_type of custom_event.
  if (messageItem.custom_event_name === 'alert_button') {
    // eslint-disable-next-line no-alert
    window.alert(messageItem.user_defined?.text);
  }
}

/**
 * Listens for workspace panel open event.
 */
function customWorkspaceOpenHandler(event: BusEvent) {
  const { data } = event as BusEventWorkspaceOpen;
  console.log(data, 'open handler');
}

export { DemoApp };

// demo/src/web-components/demo-app.ts
/*
 *  Copyright IBM Corp. 2025, 2026
 *
 *  This source code is licensed under the Apache-2.0 license found in the
 *  LICENSE file in the root directory of this source tree.
 *
 *  @license
 */

import "./DemoApp.css";
import "@carbon/web-components/es/components/ai-skeleton/index.js";
import "@carbon/ai-chat/dist/es/web-components/cds-aichat-container/index.js";
import "@carbon/ai-chat/dist/es/web-components/cds-aichat-custom-element/index.js";
import "./user-defined-response-example";
import "./custom-footer-example";
import "./writeable-element-example";
import "./workspace-writeable-element-example";
import "./history-writeable-element-example";
import "./explainability-popover-example";

import {
  BusEvent,
  BusEventMessageItemCustom,
  BusEventType,
  BusEventViewChange,
  BusEventViewPreChange,
  ChatInstance,
  GenericItem,
  PublicConfig,
  RenderUserDefinedState,
  ServiceDesk,
  ServiceDeskFactoryParameters,
  UserDefinedItem,
  ViewType,
} from "@carbon/ai-chat";
import { css, html, LitElement, PropertyValues } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import { DeepPartial } from "../types/DeepPartial";

import { Settings } from "../framework/types";
import { MockServiceDesk } from "../mockServiceDesk/mockServiceDesk";

async function sleep(milliseconds: number) {
  await new Promise((resolve) => {
    setTimeout(resolve, milliseconds);
  });
}

const serviceDeskFactory = (parameters: ServiceDeskFactoryParameters) =>
  Promise.resolve(new MockServiceDesk(parameters) as ServiceDesk);

interface CustomFooterSlotsMap {
  [key: string]: CustomFooterSlot;
}

interface CustomFooterSlot {
  messageItem: GenericItem;
  additionalData?: Record<string, unknown>;
}

/**
 * `DemoApp` is a custom Lit element representing usage of AI chat with a web component.
 */
@customElement("demo-app")
export class DemoApp extends LitElement {
  static styles = css`
    cds-ai-skeleton-placeholder {
      width: 100%;
    }

    .fullScreen {
      position: fixed;
      bottom: 0;
      right: var(--chat-position-right);
      left: var(--chat-position-left);
      height: calc(100vh - 48px);
      width: calc(100vw - 320px - 2rem);
      z-index: 9999;
    }

    .sidebar {
      position: fixed;
      right: var(--chat-position-right);
      left: var(--chat-position-left);
      top: 48px;
      height: calc(100vh - 48px);
      width: 320px;
      z-index: 9999;
      /* Carbon motion token: motion.$duration-moderate-01 (240ms) or motion.$duration-fast-01 (70ms) for RTL with motion.motion(standard, productive) */
      transition: var(--chat-sidebar-transition-property)
        var(--chat-sidebar-transition-duration)
        var(--chat-sidebar-transition-timing-function);
      visibility: visible;
    }

    .sidebar--expanded {
      width: calc(100vw - 320px - 2rem);
    }

    .sidebar--expanding {
      /* Carbon motion tokens: motion.$duration-moderate-01 (240ms) or motion.$duration-fast-01 (70ms) for RTL, and motion.$duration-moderate-02 (400ms) with motion.motion(standard, productive) */
      transition: var(--chat-sidebar-transition-property)
        var(--chat-sidebar-transition-duration)
        var(--chat-sidebar-expanding-transition-timing-function);
    }

    .sidebar--contracting {
      /* Carbon motion tokens: motion.$duration-moderate-01 (240ms) or motion.$duration-fast-01 (70ms) for RTL, and motion.$duration-moderate-02 (400ms) with motion.motion(standard, productive) */
      transition: var(--chat-sidebar-transition-property)
        var(--chat-sidebar-transition-duration)
        var(--chat-sidebar-contracting-transition-timing-function);
    }

    .sidebar--closing {
      right: var(--chat-sidebar-closing-right);
      left: var(--chat-sidebar-closing-left);
      width: 320px;
    }

    .sidebar--closed {
      right: var(--chat-sidebar-closed-right);
      left: var(--chat-sidebar-closed-left);
      width: 320px;
      visibility: hidden;
    }
  `;

  @property({ type: Object })
  accessor settings!: Settings;

  @property({ type: Object })
  accessor config!: PublicConfig;

  @property({ type: Object })
  accessor onChatInstanceReady: ((instance: ChatInstance) => void) | undefined =
    undefined;

  @state()
  accessor sideBarOpen: boolean = false;

  @state()
  accessor sideBarClosing: boolean = false;

  @state()
  accessor workspaceExpanded: boolean = false;

  @state()
  accessor workspaceAnimating: "expanding" | "contracting" | null = null;

  @state()
  accessor instance!: ChatInstance;

  @state()
  accessor customFooterSlotsMap: CustomFooterSlotsMap = {};

  @state()
  accessor valueFromParent: string = Date.now().toString();

  /**
   * Tracks user-defined-response elements created by the callback so we can
   * push parent-state updates (like valueFromParent) to them reactively.
   */
  private _userDefinedElements = new Set<HTMLElement>();

  private _interval?: ReturnType<typeof setInterval>;

  protected firstUpdated(_changedProperties: PropertyValues): void {
    // Mirrors DemoApp.tsx: continuously updates parent state to exercise live
    // host-state propagation. Skipped via `?disableParentStateTimer` so the
    // chat's render performance can be profiled without this constant noise.
    if (
      new URLSearchParams(window.location.search).has("disableParentStateTimer")
    ) {
      return;
    }
    this._interval = setInterval(() => {
      this.valueFromParent = Date.now().toString();
    }, 1500);
  }

  protected updated(changedProperties: PropertyValues): void {
    if (changedProperties.has("valueFromParent")) {
      for (const el of this._userDefinedElements) {
        if (!el.isConnected) {
          this._userDefinedElements.delete(el);
          continue;
        }
        (el as any).valueFromParent = this.valueFromParent;
      }
    }
  }

  disconnectedCallback(): void {
    super.disconnectedCallback();
    if (this._interval) {
      clearInterval(this._interval);
    }
  }

  /**
   * Listens for view changes on the AI chat.
   */
  onViewPreChange = async (
    event: BusEventViewPreChange,
    _instance: ChatInstance,
  ) => {
    if (!event.newViewState.mainWindow) {
      this.sideBarClosing = true;
      // In production, should really be using AnimationEvent event here instead of a hard coded timeout.
      await sleep(250);
    }
  };

  /**
   * Listens for view changes on the AI chat.
   */
  onViewChange = (event: BusEventViewChange, _instance: ChatInstance) => {
    if (event.newViewState.mainWindow) {
      this.sideBarOpen = true;
    } else {
      this.sideBarOpen = false;
      this.sideBarClosing = false;
    }
  };

  /**
   * Closes/hides the chat.
   */
  openSideBar = () => {
    this.instance?.changeView(ViewType.MAIN_WINDOW);
  };

  /**
   * Listens for clicks from buttons with custom events attached.
   */
  customButtonHandler = (event: BusEvent) => {
    const { messageItem } = event as BusEventMessageItemCustom;
    // The 'custom_event_name' property comes from the button response type with button_type of custom_event.
    if (messageItem.custom_event_name === "alert_button") {
      // eslint-disable-next-line no-alert
      window.alert(messageItem.user_defined?.text);
    }
  };

  /**
   * The onBeforeRender prop lets as setup our event handlers and set the instance to state so we can access it
   * whenever we need to later.
   */
  onBeforeRender = (instance: ChatInstance) => {
    this.instance = instance;

    // Notify parent component that instance is ready
    this.onChatInstanceReady?.(instance);

    this.instance.on({
      type: BusEventType.MESSAGE_ITEM_CUSTOM,
      handler: this.customButtonHandler,
    });
    // User defined responses are handled by the renderUserDefinedResponse callback
    // on the container/custom-element, so no manual event handlers needed here.
    this.instance.on({
      type: BusEventType.CUSTOM_FOOTER_SLOT,
      handler: this.customFooterHandler,
    });

    // Listen for workspace pre-open event to expand sidebar
    this.instance.on({
      type: BusEventType.WORKSPACE_PRE_OPEN,
      handler: () => {
        if (this.settings.layout === "sidebar") {
          console.log("Web Component: Expanding sidebar - workspace opening");
          this.workspaceAnimating = "expanding";
          this.workspaceExpanded = true;
        }
      },
    });

    // Listen for workspace pre-close event to contract sidebar
    this.instance.on({
      type: BusEventType.WORKSPACE_PRE_CLOSE,
      handler: () => {
        if (this.settings.layout === "sidebar") {
          console.log("Web Component: Contracting sidebar - workspace closing");
          this.workspaceAnimating = "contracting";
          this.workspaceExpanded = false;
        }
      },
    });

    // Listen for when new chat option is selected from the chat header overflow menu
    instance.on({
      type: BusEventType.HISTORY_PANEL_NEW_CHAT,
      handler: () => window.alert("Creating new chat from header menu"),
    });
  };

  /**
   * Callback to render user_defined responses. The library manages event listening, slot tracking,
   * streaming state, and element lifecycle. We just return an HTMLElement.
   *
   * We track created elements in _userDefinedElements so parent state like valueFromParent
   * can be pushed to them reactively via updated().
   */
  renderUserDefinedCallback = (
    state: RenderUserDefinedState,
  ): HTMLElement | null => {
    // Handle streaming — show partial content as it arrives
    if (state.partialItems?.length) {
      const firstChunk = state.partialItems[0] as DeepPartial<UserDefinedItem>;
      switch (firstChunk.user_defined?.user_defined_type) {
        case "green": {
          const text = state.partialItems
            .map(
              (item: DeepPartial<GenericItem>) =>
                (item as DeepPartial<UserDefinedItem>).user_defined?.text,
            )
            .join("");
          const el = document.createElement(
            "user-defined-response-example",
          ) as any;
          el.text = text;
          el.valueFromParent = this.valueFromParent;
          this._userDefinedElements.add(el);
          return el;
        }
        default:
          // Show skeleton for unknown streaming types
          return document.createElement("cds-ai-skeleton-text");
      }
    }

    // Handle complete responses
    if (state.messageItem) {
      const userDefinedMessage = state.messageItem as UserDefinedItem;
      switch (userDefinedMessage.user_defined?.user_defined_type) {
        case "green": {
          const el = document.createElement(
            "user-defined-response-example",
          ) as any;
          el.text = userDefinedMessage.user_defined.text as string;
          el.valueFromParent = this.valueFromParent;
          this._userDefinedElements.add(el);
          return el;
        }
        default:
          return null;
      }
    }

    return null;
  };

  /**
   * Each custom footer event is tied to a slot deeply rendered with-in AI chat that is generated at runtime.
   * Here we make sure we store all these slots along with their relevant data in order to be able to dynamically
   * render the content to be slotted when this.renderCustomFooterSlots() is called in the render function.
   */
  customFooterHandler = (event: any) => {
    const { data } = event;

    this.customFooterSlotsMap[data.slotName] = {
      messageItem: data.messageItem,
      additionalData: data.additionalData,
    };

    this.requestUpdate();
  };

  /**
   * This renders each of the slots that were generated by the AI chat.
   */
  renderCustomFooterSlots() {
    const customFooterSlotsKeyArray = Object.keys(this.customFooterSlotsMap);

    return customFooterSlotsKeyArray.map((slotName) => {
      const { messageItem, additionalData } =
        this.customFooterSlotsMap[slotName];

      return html`<div slot=${slotName}>
        <custom-footer-example
          .messageItem=${messageItem}
          .additionalData=${additionalData}
        ></custom-footer-example>
      </div>`;
    });
  }

  /**
   * You only need to provide the slots you want to use. In this demo, we fill them all with big
   * green boxes.
   *
   * Workspace panel element is now using the workspace-writeable-element-example component. and we render it with custom example for demo purpose. but remember its a custom slot.
   */
  renderWriteableElementSlots() {
    const ALWAYS_RENDER_KEYS = [
      "workspacePanelElement",
      "historyPanelElement",
      "explainabilityPopoverContent",
      "explainabilityPopoverActions",
    ];
    const elements = this.instance?.writeableElements ?? {};

    const keys =
      this.settings.writeableElements === "true"
        ? Object.keys(elements)
        : this.config.homescreen?.customContentOnly
          ? ["homeScreenHeaderBottomElement", "homeScreenAfterStartersElement"]
          : [];

    const finalKeys = [
      ...ALWAYS_RENDER_KEYS,
      ...keys.filter((k) => !ALWAYS_RENDER_KEYS.includes(k)),
    ];

    return finalKeys.map((key) => {
      switch (key) {
        case "explainabilityPopoverContent":
          return html`<div slot=${key}>
            <explainability-popover-content></explainability-popover-content>
          </div>`;
        case "explainabilityPopoverActions":
          return html`<div slot=${key}>
            <explainability-popover-actions></explainability-popover-actions>
          </div>`;
        case "workspacePanelElement":
          return html`<div slot=${key}>
            <workspace-writeable-element-example
              location=${key}
              .instance=${this.instance}
              .valueFromParent=${this.valueFromParent}
            ></workspace-writeable-element-example>
          </div>`;
        case "historyPanelElement":
          return html`<div slot=${key}>
            <history-writeable-element-example
              location=${key}
              .instance=${this.instance}
              .valueFromParent=${this.valueFromParent}
              .isMobile=${this.instance?.getState().customPanels.history
                .isMobile ?? false}
            ></history-writeable-element-example>
          </div>`;
        default:
          return html`<div slot=${key}>
            <writeable-element-example
              location=${key}
              valueFromParent=${this.valueFromParent}
            ></writeable-element-example>
          </div>`;
      }
    });
  }

  handleTransitionEnd = (event: TransitionEvent) => {
    // Only handle width transitions on the chat element itself
    if (
      event.propertyName === "width" &&
      event.target === event.currentTarget
    ) {
      this.workspaceAnimating = null;
    }
  };

  getSideBarClassName() {
    let className = "sidebar";
    if (this.workspaceExpanded) {
      className += " sidebar--expanded";
    }
    if (this.workspaceAnimating === "expanding") {
      className += " sidebar--expanding";
    } else if (this.workspaceAnimating === "contracting") {
      className += " sidebar--contracting";
    }
    if (this.sideBarClosing) {
      className += " sidebar--closing";
    } else if (!this.sideBarOpen) {
      className += " sidebar--closed";
    }
    return className;
  }

  // Depending on which layout is setting in settings, render the right version of AI chat.
  render() {
    return html`
      ${this.settings.layout === "float"
        ? html`<cds-aichat-container
            .config=${this.config}
            .onError=${this.config.onError}
            .openChatByDefault=${this.config.openChatByDefault ?? undefined}
            .disclaimer=${this.config.disclaimer}
            .disableCustomElementMobileEnhancements=${this.config
              .disableCustomElementMobileEnhancements ?? undefined}
            .debug=${this.config.debug ?? undefined}
            .injectCarbonTheme=${this.config.injectCarbonTheme ?? undefined}
            .aiEnabled=${this.config.aiEnabled ?? undefined}
            .shouldTakeFocusIfOpensAutomatically=${this.config
              .shouldTakeFocusIfOpensAutomatically ?? undefined}
            .namespace=${this.config.namespace ?? undefined}
            .shouldSanitizeHTML=${this.config.shouldSanitizeHTML ?? undefined}
            .header=${{
              ...this.config.header,
              hideDefaultAiLabelContent: true,
            }}
            .layout=${this.config.layout}
            .messaging=${this.config.messaging}
            .isReadonly=${this.config.isReadonly ?? undefined}
            .persistFeedback=${this.config.persistFeedback ?? undefined}
            .hideAvatar=${this.config.hideAvatar ?? undefined}
            .assistantName=${this.config.assistantName}
            .assistantAvatarUrl=${this.config.assistantAvatarUrl}
            locale=${this.config.locale}
            .homescreen=${this.config.homescreen}
            .launcher=${this.config.launcher}
            .onBeforeRender=${this.onBeforeRender}
            .serviceDeskFactory=${serviceDeskFactory}
            .renderUserDefinedResponse=${this.renderUserDefinedCallback}
            >${this.renderWriteableElementSlots()}${this.renderCustomFooterSlots()}</cds-aichat-container
          >`
        : html``}
      ${this.settings.layout === "sidebar"
        ? html`<cds-aichat-custom-element
            class=${this.getSideBarClassName()}
            @transitionend=${this.handleTransitionEnd}
            .config=${this.config}
            .onError=${this.config.onError}
            .openChatByDefault=${this.config.openChatByDefault ?? undefined}
            .disclaimer=${this.config.disclaimer}
            .disableCustomElementMobileEnhancements=${this.config
              .disableCustomElementMobileEnhancements ?? undefined}
            .debug=${this.config.debug ?? undefined}
            .injectCarbonTheme=${this.config.injectCarbonTheme ?? undefined}
            .aiEnabled=${this.config.aiEnabled ?? undefined}
            .shouldTakeFocusIfOpensAutomatically=${this.config
              .shouldTakeFocusIfOpensAutomatically ?? undefined}
            .namespace=${this.config.namespace ?? undefined}
            .shouldSanitizeHTML=${this.config.shouldSanitizeHTML ?? undefined}
            .header=${{
              ...this.config.header,
              hideDefaultAiLabelContent: true,
            }}
            .layout=${this.config.layout}
            .messaging=${this.config.messaging}
            .isReadonly=${this.config.isReadonly ?? undefined}
            .persistFeedback=${this.config.persistFeedback ?? undefined}
            .hideAvatar=${this.config.hideAvatar ?? undefined}
            .assistantName=${this.config.assistantName}
            .assistantAvatarUrl=${this.config.assistantAvatarUrl}
            locale=${this.config.locale}
            .homescreen=${this.config.homescreen}
            .launcher=${this.config.launcher}
            .onBeforeRender=${this.onBeforeRender}
            .onViewPreChange=${this.onViewPreChange}
            .onViewChange=${this.onViewChange}
            .serviceDeskFactory=${serviceDeskFactory}
            .renderUserDefinedResponse=${this.renderUserDefinedCallback}
            >${this.renderWriteableElementSlots()}${this.renderCustomFooterSlots()}</cds-aichat-custom-element
          >`
        : html``}
      ${this.settings.layout === "fullscreen"
        ? html`<cds-aichat-custom-element
            class="fullScreen"
            .config=${this.config}
            .onError=${this.config.onError}
            .openChatByDefault=${this.config.openChatByDefault ?? undefined}
            .disclaimer=${this.config.disclaimer}
            .disableCustomElementMobileEnhancements=${this.config
              .disableCustomElementMobileEnhancements ?? undefined}
            .debug=${this.config.debug ?? undefined}
            .injectCarbonTheme=${this.config.injectCarbonTheme ?? undefined}
            .aiEnabled=${this.config.aiEnabled ?? undefined}
            .shouldTakeFocusIfOpensAutomatically=${this.config
              .shouldTakeFocusIfOpensAutomatically ?? undefined}
            .namespace=${this.config.namespace ?? undefined}
            .shouldSanitizeHTML=${this.config.shouldSanitizeHTML ?? undefined}
            .header=${{
              ...this.config.header,
              hideDefaultAiLabelContent: true,
            }}
            .layout=${this.config.layout}
            .messaging=${this.config.messaging}
            .isReadonly=${this.config.isReadonly ?? undefined}
            .assistantName=${this.config.assistantName}
            .assistantAvatarUrl=${this.config.assistantAvatarUrl}
            locale=${this.config.locale}
            .homescreen=${this.config.homescreen}
            .launcher=${this.config.launcher}
            .onBeforeRender=${this.onBeforeRender}
            .serviceDeskFactory=${serviceDeskFactory}
            .renderUserDefinedResponse=${this.renderUserDefinedCallback}
            .hideAvatar=${this.config.hideAvatar ?? undefined}
            >${this.renderWriteableElementSlots()}${this.renderCustomFooterSlots()}</cds-aichat-custom-element
          >`
        : html``}
    `;
  }
}

// Register the custom element if not already defined
declare global {
  interface HTMLElementTagNameMap {
    "demo-app": DemoApp;
  }
}
