// examples/react/workspace/src/InventoryStatusExample.tsx
/*
 *  Copyright IBM Corp. 2026
 *
 *  This source code is licensed under the Apache-2.0 license found in the
 *  LICENSE file in the root directory of this source tree.
 *
 *  @license
 */
import "./WorkspaceWriteableElementExample.css";
import WorkspaceShell, {
  WorkspaceShellHeader,
  WorkspaceShellBody,
  WorkspaceShellFooter,
} from "@carbon/ai-chat-components/es/react/workspace-shell.js";
import Toolbar from "@carbon/ai-chat-components/es/react/toolbar.js";

// Using @carbon/icons-react for all icons
import Close16 from "@carbon/icons-react/es/Close.js";

import React, { useState } from "react";
import { ChatInstance, PanelType } from "@carbon/ai-chat";
import { AILabel, Tag } from "@carbon/react";

interface InventoryStatusExampleProps {
  location: string;
  instance: ChatInstance;
  workspaceId?: string;
  additionalData?: any;
}

function InventoryStatusExample({
  location,
  instance,
  workspaceId,
  additionalData,
}: InventoryStatusExampleProps) {
  const handleClose = () => {
    panel?.close();
  };

  const [toolbarActions, _setToolbarActions] = useState([
    {
      id: "close",
      text: "Close",
      fixed: true,
      icon: Close16,
      onClick: handleClose,
    },
  ]);

  const [footerActions, _setFooterActions] = useState([
    {
      id: "evaluate",
      label: "Evaluate plan",
      kind: "secondary",
      payload: { test: "value" },
    },
    {
      id: "run",
      label: "Run plan",
      kind: "primary",
      payload: { test: "value" },
    },
    {
      id: "cancel",
      label: "Cancel",
      kind: "ghost",
      payload: { test: "value" },
    },
  ]);

  const panel = instance?.customPanels?.getPanel(PanelType.WORKSPACE);

  const handleWorkspaceFooterClick = (event: any) => {
    const { id, kind, label, payload } = event.detail;
    switch (id) {
      case "evaluate":
        alert(
          `Evaluate plan clicked. Kind: ${kind}, Label: ${label}, Payload: ${JSON.stringify(payload)}`,
        );
        break;
      case "run":
        alert(
          `Run plan clicked. Kind: ${kind}, Label: ${label}, Payload: ${JSON.stringify(payload)}`,
        );
        break;
      case "cancel":
        handleClose();
        break;
      default:
        return;
    }
  };

  return (
    <WorkspaceShell>
      <Toolbar slot="toolbar" actions={toolbarActions} overflow>
        <div slot="title" data-fixed>
          Current inventory status
        </div>
        <AILabel size="2xs" autoAlign={false} align="bottom">
          <h4 className="margin-bottom-05">Powered by IBM watsonx</h4>
          <div>
            IBM watsonx is powered by the latest AI models to intelligently
            process conversations and provide help whenever and wherever you may
            need it.
          </div>
        </AILabel>
      </Toolbar>
      <WorkspaceShellHeader
        titleText="Current inventory status"
        subTitleText={`Created on: ${new Date().toLocaleDateString()}`}
      >
        <div slot="header-description">
          This is a simple example workspace component demonstrating the data
          flow from preview card to workspace.
        </div>
        <div slot="header-description">
          <Tag size="sm" type="blue">
            Type: inventory_status
          </Tag>
        </div>
      </WorkspaceShellHeader>
      <WorkspaceShellBody>
        <h3>Hello World!</h3>
        <p>
          This is the <strong>InventoryStatusExample</strong> component,
          rendered when <code>additional_data.type</code> is{" "}
          <code>inventory_status</code>.
        </p>
        <br />
        <h4>Data Flow Demonstration:</h4>
        <p>
          Location: <strong>{location}</strong>
        </p>
        <p>
          Workspace ID: <strong>{workspaceId || "Not provided"}</strong>
        </p>
        <br />
        <h4>Additional Data from Preview Card:</h4>
        <pre>{JSON.stringify(additionalData, null, 2)}</pre>
        <br />
        <p>
          This demonstrates how data flows from the preview cards{" "}
          <code>additional_data</code> field all the way to the workspace
          component, allowing you to pass custom data and configuration to your
          workspace templates.
        </p>
      </WorkspaceShellBody>
      <WorkspaceShellFooter
        onFooterClicked={handleWorkspaceFooterClick}
        actions={footerActions}
      ></WorkspaceShellFooter>
    </WorkspaceShell>
  );
}

export { InventoryStatusExample };

// Made with Bob

// examples/web-components/workspace-sidebar/src/inventory-status-example.ts
/*
 *  Copyright IBM Corp. 2026
 *
 *  This source code is licensed under the Apache-2.0 license found in the
 *  LICENSE file in the root directory of this source tree.
 *
 *  @license
 */

import { css, html, LitElement } from "lit";
import { customElement, property } from "lit/decorators.js";
import "@carbon/web-components/es/components/button/index.js";
import { PanelType } from "@carbon/ai-chat";
import "@carbon/ai-chat-components/es/components/workspace-shell/index.js";
import "@carbon/ai-chat-components/es/components/toolbar/index.js";
import "@carbon/web-components/es/components/tag/tag.js";
import "@carbon/web-components/es/components/ai-label/ai-label.js";
//icons
import Close16 from "@carbon/icons/es/close/16.js";

@customElement("inventory-status-example")
class InventoryStatusExample extends LitElement {
  static styles = css`
    pre {
      background: #f4f4f4;
      padding: 1rem;
      border-radius: 4px;
      overflow: auto;
      max-height: 200px;
    }
  `;

  @property({ type: String })
  accessor location: string = "";

  @property({ type: Object })
  accessor instance: any = null;

  @property({ type: String })
  accessor workspaceId: string = "";

  @property({ type: Object })
  accessor additionalData: any = null;

  @property({ type: Array })
  accessor toolbarActions: any[] = [
    {
      text: "Close",
      fixed: true,
      icon: Close16,
      size: "md",
      onClick: this.handleClose.bind(this),
    },
  ];

  @property({ type: Array })
  accessor footerActions: any[] = [
    {
      id: "evaluate",
      label: "Evaluate plan",
      kind: "secondary",
      payload: { test: "value" },
    },
    {
      id: "run",
      label: "Run plan",
      kind: "primary",
      payload: { test: "value" },
    },
    {
      id: "cancel",
      label: "Cancel",
      kind: "ghost",
      payload: { test: "value" },
    },
  ];

  handleClose() {
    const panel = this.instance?.customPanels?.getPanel(PanelType.WORKSPACE);
    panel?.close();
  }

  handleWorkspaceFooterClick(event: any) {
    const { id, kind, label, payload } = event.detail;
    switch (id) {
      case "evaluate":
        alert(
          `Evaluate plan clicked. Kind: ${kind}, Label: ${label}, Payload: ${JSON.stringify(payload)}`,
        );
        break;
      case "run":
        alert(
          `Run plan clicked. Kind: ${kind}, Label: ${label}, Payload: ${JSON.stringify(payload)}`,
        );
        break;
      case "cancel":
        this.handleClose();
        break;
      default:
        return;
    }
  }

  render() {
    return html` <cds-aichat-workspace-shell>
      <cds-aichat-toolbar
        slot="toolbar"
        overflow
        .actions=${this.toolbarActions}
      >
        <div slot="title" data-fixed>Current inventory status</div>
        <cds-ai-label slot="decorator" alignment="bottom" size="2xs">
          <div slot="body-text">
            <p class="secondary">
              IBM watsonx is powered by the latest AI models to intelligently
              process conversations and provide help whenever and wherever you
              may need it.
            </p>
          </div>
        </cds-ai-label>
      </cds-aichat-toolbar>
      <cds-aichat-workspace-shell-header
        title-text="Current inventory status"
        subtitle-text=${`Created on: ${new Date().toLocaleDateString()}`}
      >
        <div slot="header-description">
          This is a simple example workspace component demonstrating the data
          flow from preview card to workspace.
        </div>
        <div slot="header-description">
          <cds-tag size="sm" type="blue">Type: inventory_status</cds-tag>
        </div>
      </cds-aichat-workspace-shell-header>
      <cds-aichat-workspace-shell-body>
        <h3>Hello World!</h3>
        <p>
          This is the <strong>InventoryStatusExample</strong> component,
          rendered when <code>additional_data.type</code> is
          <code>"inventory_status"</code>.
        </p>
        <br />
        <h4>Data Flow Demonstration:</h4>
        <p>Location: <strong>${this.location}</strong></p>
        <p>
          Workspace ID:
          <strong>${this.workspaceId || "Not provided"}</strong>
        </p>
        <br />
        <h4>Additional Data from Preview Card:</h4>
        <pre>${JSON.stringify(this.additionalData, null, 2)}</pre>
        <br />
        <p>
          This demonstrates how data flows from the preview card's
          <code>additional_data</code> field all the way to the workspace
          component, allowing you to pass custom data and configuration to your
          workspace templates.
        </p>
      </cds-aichat-workspace-shell-body>

      <cds-aichat-workspace-shell-footer
        .actions=${this.footerActions}
        @cds-aichat-workspace-shell-footer-clicked=${
          this.handleWorkspaceFooterClick
        }
      >
      </cds-aichat-workspace-shell-footer>
    </cds-aichat-workspace-shell>`;
  }
}

export default InventoryStatusExample;

// Made with Bob
